import fs from 'fs';
import Sanscript from '@indic-transliteration/sanscript';

const translationsFile = 'scratch/translations_6.json';
const translations = JSON.parse(fs.readFileSync(translationsFile, 'utf8'));

const targetLangs = ['en', 'hi', 'kn', 'ta', 'te'];
const langToScript = {
  'en': 'iast',
  'hi': 'devanagari',
  'kn': 'kannada',
  'ta': 'tamil',
  'te': 'telugu'
};

const replacements = [
  {
    en: "Falsity is not absolute non-existence, due to contradiction of doctrine.",
    hi: "मिथ्यात्व अत्यन्तासत् नहीं है, क्योंकि इससे अपसिद्धान्त होता है।",
    kn: "ಮಿಥ್ಯಾತ್ವವು ಅತ್ಯಂತಾಸತ್ ಅಲ್ಲ, ಏಕೆಂದರೆ ಇದರಿಂದ ಅಪಸಿದ್ಧಾಂತವಾಗುತ್ತದೆ.",
    ta: "மித்யாத்வம் என்பது முற்றிலும் இல்லாதது அல்ல, ஏனெனில் இதனால் அபசித்தாந்தம் ஏற்படும்.",
    te: "మిథ్యాత్వం అంటే అత్యంత అసత్తు కాదు, ఎందుకంటే దీనివల్ల అపసిద్ధాంతం అవుతుంది.",
    sa: "मिथ्यात्वं च यद्यपि नात्यन्तासत्त्वम्, अपसिद्धान्तात् ।"
  },
  {
    en: "Nor is it indefinability, as it is unestablished.",
    hi: "यह अनिर्वाच्य भी नहीं है, क्योंकि यह अप्रसिद्ध है।",
    kn: "ಇದು ಅನಿರ್ವಾಚ್ಯವೂ ಅಲ್ಲ, ಏಕೆಂದರೆ ಇದು ಅಪ್ರಸಿದ್ಧವಾಗಿದೆ.",
    ta: "இது அநிர்வாச்யமல்ல, ஏனெனில் இது உலகில் அறியப்படாதது.",
    te: "ఇది అనిర్వాచ్యం కాదు, ఎందుకంటే ఇది అప్రసిద్ధం.",
    sa: "नाप्यनिर्वाच्यत्वम्, अप्रसिद्धेः ।"
  },
  {
    en: "Nor is it difference from the real, because even a real object is different from another real object.",
    hi: "यह सत् से भिन्नता भी नहीं है, क्योंकि एक सत् वस्तु भी दूसरी सत् वस्तु से भिन्न होती है।",
    kn: "ಇದು ಸತ್ ನಿಂದ ಭಿನ್ನತೆಯೂ ಅಲ್ಲ, ಏಕೆಂದರೆ ಒಂದು ಸತ್ ವಸ್ತುವು ಮತ್ತೊಂದು ಸತ್ ವಸ್ತುವಿನಿಂದಲೂ ಭಿನ್ನವಾಗಿರುತ್ತದೆ.",
    ta: "இது சத்திலிருந்து வேறுபட்டிருப்பது அல்ல, ஏனெனில் ஒரு சத் பொருளும் மற்றொரு சத் பொருளிலிருந்து வேறுபட்டது.",
    te: "ఇది సత్తు నుండి భిన్నంగా ఉండటం కాదు, ఎందుకంటే ఒక సత్తు వస్తువు మరొక సత్తు వస్తువు నుండి భిన్నంగా ఉంటుంది.",
    sa: "नापि सद्विविक्तत्वम्, सतोऽपि सदन्तरविविक्तत्वात् ।"
  },
  {
    en: "Because even the attribute-less Brahman has it.",
    hi: "क्योंकि निर्धर्मक ब्रह्म में भी यह है।",
    kn: "ಏಕೆಂದರೆ ನಿರ್ಧರ್ಮಕ ಬ್ರಹ್ಮನಲ್ಲಿಯೂ ಇದು ಇದೆ.",
    ta: "ஏனெனில் நிர்குணமான பிரம்மத்திலும் இது அதிவ்யாப்தி ஆகும்.",
    te: "ఎందుకంటే నిర్ధర్మకమైన బ్రహ్మలో కూడా ఇది ఉంటుంది.",
    sa: "निर्धर्मके ब्रह्मण्यपि सत्त्वात् ।"
  },
  {
    en: "Nor can it be said...",
    hi: "यह भी नहीं कहा जा सकता...",
    kn: "ಇದು ಕೂಡ ಹೇಳಲಾಗದು...", // wait, kn did not translate this line perfectly
    ta: "இப்படியும் கூற முடியாது...",
    te: "ఇలా కూడా చెప్పలేము...",
    sa: "न च ... इति वाच्यम्"
  },
  {
    en: "Otherwise, the absence of non-existence would also...",
    hi: "अन्यथा, असत्त्वानधिकरणत्व का भी...",
    kn: "ಇಲ್ಲದಿದ್ದರೆ, ಅಸತ್ವಾನಧಿಕರಣತ್ವವೂ...",
    ta: "இல்லையென்றால், அசத்வானதிகரணத்வமும்...",
    te: "లేకపోతే, అసత్వానధికరణత్వం కూడా...",
    sa: "अन्यथाऽसत्त्वानधिकरणत्वस्यापि..."
  },
  {
    en: "It is not being un-objectifiable by valid knowledge, because Brahman is pervaded by the mental modification generated by Vedanta.",
    hi: "यह प्रमा का अविषय होना नहीं है, क्योंकि ब्रह्म वेदान्तजन्य वृत्ति का व्याप्य है।",
    kn: "ಬ್ರಹ್ಮವು ವೇದಾಂತಜನ್ಯ ವೃತ್ತಿಯ ವ್ಯಾಪ್ಯವಾಗಿದೆ.",
    ta: "பிரம்மம் வேதாந்தத்தின் மூலம் அறியப்படுகிறது.",
    te: "బ్రహ్మము వేదాంతజన్య వృత్తికి విషయమవుతుంది.",
    sa: "न च प्रमित्यविषयत्वं मिथ्यात्वम्, ब्रह्म तु वेदान्तजन्यवृत्तिव्याप्यमिति वाच्यम् ।"
  },
  {
    en: "And even shell-silver is an object through primary cognition and for secondary cognition, and directly as the object of negation for sublating knowledge.",
    hi: "और शुक्ति-रजत आदि भी व्यवसाय और अनुव्यवसाय के द्वारा तथा बाधक ज्ञान के प्रति निषेध्य रूप में साक्षात् ज्ञान के विषय होते ही हैं।",
    kn: "ಮತ್ತು ಚಿಪ್ಪಿನ ಬೆಳ್ಳಿಯೂ ಸಹ ಜ್ಞಾನಕ್ಕೆ ವಿಷಯವಾಗುತ್ತದೆ.",
    ta: "மேலும் சிப்பியில் உள்ள வெள்ளியும் அறிவுக்குப் பொருளாகிறது.",
    te: "మరియు ముత్యపు చిప్పలోని వెండి కూడా జ్ఞానానికి విషయమవుతుంది.",
    sa: "शुक्तिरूप्यादेरपि व्यवसायद्वारा अनुव्यवसायं प्रति साक्षाच्च बाधकज्ञानं प्रति निषेध्यत्वेन विषयत्वात् ।"
  },
  {
    en: "If it means not being directly the object of valid knowledge where reality is the chief qualifier...",
    hi: "यदि इसका अर्थ सत्यत्व प्रकारक प्रमा के प्रति साक्षात् अविषयत्व है...",
    kn: "ಸತ್ಯತ್ವ ಪ್ರಕಾರಕ ಪ್ರಮೆಗೆ ಸಾಕ್ಷಾತ್ ಅವಿಷಯತ್ವ ಎಂದಾದರೆ...",
    ta: "சத்தியமாக அறிவுக்குப் பொருளாகாததே மித்யாத்வம் என்றால்...",
    te: "సత్యంగా జ్ఞానానికి విషయం కాకపోవడమే మిథ్యాత్వం అంటే...",
    sa: "सत्त्वप्रकारकप्रमां प्रति साक्षादविषयत्वं चेद्..."
  },
  {
    en: "Due to parsimony, falsity would simply be the absence of existence.",
    hi: "लाघव के कारण सत्त्व का अभाव ही मिथ्यात्व सिद्ध होगा।",
    kn: "ಲಾಘವದಿಂದ ಅದರ ಅರ್ಥ - ಸತ್ಯತೆಯ ಅಭಾವ.",
    ta: "அதன் எளிய பொருள் சத்தியம் இல்லாதது.",
    te: "సులభంగా దాని అర్థం సత్యత లేకపోవడం.",
    sa: "आवश्यकत्वात् सत्त्वाभाव एव मिथ्यात्वं स्यात् ।"
  }
];

targetLangs.forEach(lang => {
  let content = translations['6.md'][lang][0];
  const script = langToScript[lang];
  
  replacements.forEach(rep => {
    if (rep[lang]) {
      let transliterated = rep.sa;
      if (script !== 'devanagari') {
        transliterated = Sanscript.t(rep.sa, 'devanagari', script);
      }
      // Replace only exact quotes by wrapping in **" "**
      const searchStr = `**"${rep[lang]}"**`;
      const replaceStr = `**"${transliterated}"**`;
      
      // Also try replacing without quotes just in case
      content = content.replace(searchStr, replaceStr);
      // For some cases where quotes might not be present but bold is:
      content = content.replace(`**${rep[lang]}**`, `**${transliterated}**`);
    }
  });
  
  translations['6.md'][lang][0] = content;
});

fs.writeFileSync(translationsFile, JSON.stringify(translations, null, 2));
console.log('Updated translations_6.json with transliterated Nyayamrutam quotes in dialogue.');
